name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Puedes especificar cualquier otra rama que desees.

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Agregar tu DockerHub user en los secretos
        password: ${{ secrets.DOCKER_PASSWORD }}  # Agregar tu DockerHub password en los secretos

    - name: Build and push Docker image
      run: |
        docker build -t alexismendozaa/delishub:latest .
        docker push alexismendozaa/delishub:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to EC2 using SSH
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}  # IP pública de tu EC2
        username: ubuntu  # Usuario por defecto de EC2, puede variar
        key: ${{ secrets.EC2_SSH_KEY }}  # La clave privada SSH en los secretos
        port: 22
        script: |
          # Detener el contenedor si ya existe
          docker stop your_container_name || true
          docker rm your_container_name || true
          # Descargar la última imagen de Docker desde DockerHub
          docker pull alexismendozaa/delishub:latest
          # Iniciar el contenedor
          docker run -d --name your_container_name -p 80:80 alexismendozaa/delishub:latest
